### ISSUE TITLE
Question about the code concept

### ISSUE THREAD

**Issue by Jinhao218** [Yeuyo/GNLSFEA#1]
DearYeuyo

Thanks for you great work on nonlinear FEA. I can not open “ http://www.eccm-ecfd2018.org/admin/files/filePaper/p1373.pdf “ about the code concept. Could you share this concept or update this address ?

Thanks a lot.

Best regards
Jinhao

**Comment by Yeuyo** [comment]
Dear Jinhao,

Could you try this link instead?
https://openaccess.city.ac.uk/id/eprint/21907/1/p1373.pdf

Sorry for any inconvenience caused.

Regards,
Yew Wong

**Comment by Jinhao218** [comment]
Dear Yew


Thanks for your help. This link is valid.&nbsp;


This paper is a very great work. Thanks for your sharing.


And I am looking forward to your another work "Thesis:&nbsp;This is a work in progress, a detailed ReadMe will be updated by the end of January 2020." in GitHub.


A detailed ReadMe is very helpful to understand the Matlab code of Thesis in GitHub.


Thanks a lot.


Best regards
Jinhao










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yeuyo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 晚上9:12
收件人:&nbsp;"Yeuyo/GNLSFEA"<GNLSFEA@noreply.github.com&gt;;
抄送:&nbsp;"张晋豪"<814457959@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Yeuyo/GNLSFEA] Question about the code concept (#1)




Dear Jinhao,
 
Could you try this link instead?
 https://openaccess.city.ac.uk/id/eprint/21907/1/p1373.pdf
 
Sorry for any inconvenience caused.
 
Regards,
 Yew Wong
